name: checkout

#on: [push]
on:
  push:
    branches-ignore:
      - '**'
jobs:
  checkout-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: ls -al
      run: | 
        ls -al
