on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    #name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: actions/github-action-sample@v1 # change repository name
      with:
        who-to-greet: 'suzucan2020'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
