name: upload-download-artifact
on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir dataecho "Hello" > data/hello.txt
      - uses: actions/upload-artifact@v2
        with:
          name: data
          path: data
  download:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: data
      - run: |
          ls -al
          cat hello.txt
